require('plugns/lsp')
require('plugns/telescope')
require('plugns/airline')
require('plugns/gitsigns')
require('plugns/treesitter')
-- require('plugns/nvim-tree')
require('plugns/vimwiki')
require('plugns/nerdtree')
require('plugns/neofsharp')
require('plugns/mason')
require('plugns/spellsitter')
require('plugns/indent-blankline')
require('plugns/lualine')
